name: ethereum-provider-js-ci

on:
  pull_request:
    paths:
      - "provider/implementations/ethereum-provider-js/**"

jobs:
  ci:
    name: ethereum-provider-js-ci
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
        working-directory: ./provider/implementations/ethereum-provider-js

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
        working-directory: ./provider/implementations/ethereum-provider-js

      - name: Build
        run: yarn build
        working-directory: ./provider/implementations/ethereum-provider-js

      - name: Test
        run: yarn test
        working-directory: ./provider/implementations/ethereum-provider-js